// src/views/Home/ProjectComponent.vue
<script setup>
import { ArrowTopRightOnSquareIcon } from "@heroicons/vue/20/solid"

const props = defineProps({
  project: Object,
  sequence: Number,
})
</script>

<template>
  <div class="my-16 card bg-slate-50">
    <img
      :src="`/images/projects/${project.image}`"
      :alt="project.name"
      :title="project.name"
      class="md:hidden"
    />
    <div class="flex gap-8">
      <div class="card-body">
        <h4 class="card-title">{{ project.name }}</h4>
        <p class="card-text">{{ project.description }}</p>
        <ul class="px-3">
          <li v-for="link in project.links" :key="link.name">
            <a :href="link.url" target="_blank">
              {{ link.name }}
              <ArrowTopRightOnSquareIcon class="inline w-4" />
            </a>
          </li>
        </ul>
        <div class="flex justify-center gap-5 p-5 md:justify-start">
          <img
            v-for="skill in project.skills"
            :key="skill.name"
            :src="`/images/skills/${skill.icon}`"
            :alt="skill.name"
            :title="skill.name"
            class="w-8 h-8 border"
          />
        </div>
      </div>
      <img
        :src="`/images/projects/${project.image}`"
        :alt="project.name"
        :title="project.name"
        class="hidden md:h-48 md:w-48 md:m-3 md:block lg:h-64 lg:w-64 lg:m-0"
        :class="{ 'order-first': sequence % 2 != 0 }"
      />
    </div>
  </div>
</template>

// src/app/components/project/project.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Project } from '../../models/project';

@Component({
	selector: 'app-project',
	templateUrl: './project.component.html',
	styleUrls: ['./project.component.css']
})
export class ProjectComponent implements OnInit {

	@Input() project: Project;

	constructor() { }

	ngOnInit(): void {
	}

}

<div class="card {{ project.Favorite ? 'border-warning' : '' }} my-3">
	<a target="_blank" href="{{ project.Url }}"><img class="card-img-top" src="/assets/projects/{{ project.Image }}" alt="{{ project.Name }}" title="{{ project.Name }}"></a>
	<div class="card-body">
		<h5 class="card-title">{{ project.Name }}</h5>
		<img *ngFor="let skill of project.Skills" src="/assets/skills/{{ skill.Icon }}" alt="{{ skill.Name }}" title="{{ skill.Name }}" class="icon" />
		<span class="card-text float-right d-none d-sm-block">{{ project.Date }}</span>
		<p class="card-text text-center" innerHTML="{{ project.Description }}"></p>
	</div>
</div>
